global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.29.150:8082']
        labels:
          application: 'Movie Booking Application'
